media:
  input: src/media
  output: /media

content:
  - name: posts
    label: Posts
    type: collection
    path: src/posts
    filename: "{year}-{month}-{day}-{primary}.md"
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: date, label: Date, type: date, required: true }
      - { name: body, label: Body, type: rich-text }

  - name: homepage
    label: Home
    type: file
    path: src/index.md
